name: Realtor Runner
on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '*/15 * * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    name: Realtor lookup
    steps:
      - name: Check it out
        uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          architecture: x64
      - uses: actions/cache@v2
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ env.pythonLocation }}-${{ hashFiles('requirements.txt') }}
      - name: Install requirements
        run: |
            pip install -r requirements.txt
      - name: Scrape it
        run: |
            python runner.py
        env:
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
          POTATO: ${{ secrets.POTATO }}
      - uses: EndBug/add-and-commit@v7
        with:
          default_author: github_actions